### ISSUE TITLE
clion project

### ISSUE THREAD

**Issue by Arthedian** [cmason1978/esp32-examples#2]
Hello,
I am trying to open your project in clion on Windows.  And throws me this error:
`Cannot get compiler information:
	Cannot run program "xtensa-esp32-elf-gcc" (in directory "C:\msys32\home\berti\esp32-examples\cmake-build-debug"): CreateProcess error=2, The system cannot find the file specified`

I changed the path for xtensa-esp32-elf-gcc, but its not working I tried `C:\\msys32\\opt\\xtensa-esp32-elf\\xtensa-esp32-elf\\` and `C:\\msys32\\opt\\xtensa-esp32-elf\\` and both doesnt work. Which is right?

**Comment by jeffrizzo** [comment]
I may well have found your (the repo owner - masoncj) repo the same way - I'd love it if you could add a "How to use CLion with this repo" section or something.  The CMake nonsense kept me away from it for a while, but your addition of a CMakeLists.txt was pretty helpful...

**Comment by joshuahaertel** [comment]
Assuming you've followed the steps here: https://esp-idf.readthedocs.io/en/latest/get-started/index.html#setup-toolchain, you should have a binary somewhere called `xtensa-esp32-elf-gcc`. I would have expected CMake to use this (appropriately modified) line to find that binary:
```
set(CMAKE_FIND_ROOT_PATH /usr/local/xtensa-esp32-elf/)
```
That was not the case for me. A good enough workaround has been to just put the full path of the `xtensa-esp32-elf-gcc` binary in the `CMAKE_C_COMPILER` variable. Something like this:
```
set(CMAKE_C_COMPILER /usr/local/esp/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc)
```
